const { Pool } = require('pg')
require("dotenv").config();

  // https://node-postgres.com/guides/async-express

  const devConfig = {
  user: process.env.PGUSER,
  host: process.env.PGHOST,
  database: process.env.PGDATABASE,
  password: process.env.PGPASSWORD,
  port: process.env.PGPORT,
}

// process.env.DATABASE_URL is generated by heroku 
const prodConfig = process.env.DATABASE_URL; // <<heroku addons

// const pool = new Pool(devConfig) 

const pool = new Pool(
      process.env.NODE_ENV === "production" ? prodConfig : devConfig
) 

//connects to postgres database
module.exports = {
  query: (text, params) => pool.query(text, params),
}





